#!/usr/bin/env python
from __future__ import print_function
from plumbum import cli, local, FG, SshMachine
from pnldash_config import *
import csv
import yaml
import sys
from plumbum.path.utils import copy
from pnldash_lib import *
from os.path import exists
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE,SIG_DFL)

import logging
logging.basicConfig(
            level=logging.INFO,
            format='%(levelname)s:%(name)s: %(message)s',
            datefmt="%Y-%m-%d %H:%M")
log = logging.getLogger(__name__)


class App(cli.Application):
    def main(self, *args):
        if args:
            print("Unknown command {0!r}".format(args[0]))
            return 1
        if not self.nested_command:
            print("No command given")
            return 1


@App.subcommand("db")
class Db(cli.Application):
    def main(self, *args):
        if args:
            print("Unknown command {0!r}".format(args[0]))
            return 1
        if not self.nested_command:
            print("No command given")
            return 1



@App.subcommand("find")
class Find(cli.Application):

    echo = cli.Flag(
        ['-e', '--echo'], default=False, help="Print files to stdout as well")

    def main(self):
        make_find(self.echo, useCache=False)


@App.subcommand("paths")
class Paths(cli.Application):
    """Updates pipeline paths (use if newly generated paths available)"""

    def main(self):
        PATHS_CSV.delete()
        make_csvs()


@App.subcommand("extra")
class Extra(cli.Application):
    """Prints unaccounted files."""

    def main(self):
        # make sure extra cache file is up to date
        dfextra = make_extra()
        if dfextra.empty:
            print('No unaccounted files.', file=sys.stderr)
        print('\n'.join(sorted(dfextra['path'].values)))


if __name__ == '__main__':
    if not CACHE_DIR.exists():
        log.info("Running for the first time, might take a few minutes to generate the cache files.")
        CACHE_DIR.mkdir()
    import pnldash_cli.ls
    import pnldash_cli.init
    import pnldash_cli.db.push
    import pnldash_cli.status
    App.subcommand("status", pnldash_cli.status.Status)
    App.subcommand("ls", pnldash_cli.ls.Ls)
    App.subcommand("init", pnldash_cli.init.Init)
    Db.subcommand("push", pnldash_cli.db.push.Push)
    App.run()
