---
title: "Flexdashboard"
output:
  flexdashboard::flex_dashboard:
      navbar:
      - { title: "PNL Project Dashboard Test", align: right }
      source_code: embed
      orientation: columns
always_allow_html: yes
---

```{r setup, include=FALSE}
library(data.table)
library(DT)
library(magrittr)
library(flexdashboard)
library(knitr)
```

Overview
=====================================

```{r}
paths <- fread("paths.csv")
diffPaths <- fread("diffPaths.csv")
paths.byProject = paths[paths[,exists],.('project files (G)'=sum(sizeMB)/1024),by=projectPath]
diffPaths.byProject = diffPaths[,.('extra files (G)'=sum(sizeMB)/1024), by=projectPath]
table = merge(paths.byProject, diffPaths.byProject, by="projectPath")
DT::datatable(table, options = list(bPaginate=F)) %>% DT::formatRound(c('project files (G)', 'extra files (G)'), 1)
```

```{r include=FALSE}
paths <- fread('paths.csv')
params <- fread('params.csv')
paths.grouped <- paths[,.(completed=sum(exists), missing=sum(not(exists)), total=.N, 'size (G)'=sum(sizeMB, na.rm=T)/1024), by=.(projectPath, pathKey, paramId)]

indentText <- function(text) {
  paste0("    ", gsub("\n", "\n    ", text))
}

library(xtable)

summarizePipeline <- function(projectpath, projectSD) {
  pipelinesSummary = projectSD[,
          {
          paramid=paramId
          paramCombo = params[projectPath==projectpath & paramId==paramid,]
          pipelineDescription = paramCombo[param=="description",paramValue]
          if (length(pipelineDescription) == 0) {
            pipelineDescription = paramCombo[param=="_description",paramValue]
          }
          if (length(pipelineDescription) == 0) {
            pipelineDescription = "None"
          }
          paramCombo = paramCombo[param != "description" & param != "_description"]
          setorder(paramCombo, param)
          paramTable = kable(paramCombo[,.(parameter=param, "parameter value"=paramValue)])
          if (nrow(paramCombo) == 0) {
            paramTable = "None given."
          }
          pathsSummary = kable(.SD, digits=1)
          knit_expand(text='### <b>PIPELINE #{{paramId}}</b>
#### Description
      {{pipelineDescription}}

#### Parameters
{{paramTable}}

#### Output Paths
{{pathsSummary}}')
          }, by=.(paramId)][,V1]

  pageHeader = knit_expand(text='# {{projectpath}} {data-navmenu="Projects"}')
  # Add leading 4 spaces to make description a markdown quotation block, hence preserving its formatting
  projectDescription = indentText(params[projectPath==projectpath,description][1])
  ## projectSummary =
  rowSep = "--------------"
  projectOverview = c("Row1", rowSep, "### **Description**", projectDescription)
  c(pageHeader, projectOverview, "  ", "Row2 {.tabset}  ", rowSep, pipelinesSummary)
}

out = paths.grouped[,
  {
  summarizePipeline(projectPath, .SD)
  }
  , by=.(projectPath)][,V1]

```

`r paste(out, collapse = '\n')`


All Project Files
=====================================

```{r}
d <- fread("paths.csv")[1:1000][,modtime:=modtimeStr][,modtimeStr:=NULL]
setorder(d, -exists, -sizeMB)
DT::datatable(d, filter = 'top', options = list(bPaginate=F)) %>% formatRound('sizeMB', 1)
```


All Extra Files
=====================================

```{r}
d <- fread("diffPaths.csv")
setorder(d, -sizeMB)
DT::datatable(d, options = list(bPaginate=F)) %>% formatRound('sizeMB', 1)
```
